Repository Soumya-Kushwaha/SoundScape, pull requests merged in 2024-06, with the labels that each got.

#97 Added Main landing page to the SoundScape Application
  Amplitude-Frequency-Visualizer.py
  Intensity-vs-Frequency-and-time.py
  Spectogram.py
  Waveform.py
  mainLanding.py
Labels: enhancement, gssoc, level2

#64 Added model for noise reduction-PCEN
  PCEN-noise_reduction.ipynb
Labels: gssoc

#107 Developed an another file for Real Time Volume Unit (VU) Tracker
  Real-Time VU Meter.py
Labels: enhancement, new visualizer, level2

#18 [feature] Issue Template for 'new visualizer' #12
  .github/ISSUE_TEMPLATE/new_visualizer.md
Labels: documentation, good first issue, gssoc, level1

#92 feat: add codeql workflow for `python`
  .github/workflows/codeql.yml
Labels: good first issue, gssoc

#100 new features,optimzation,bug fixes
  Amplitude-Frequency-Visualizer.py
  Intensity-vs-Frequency-and-time.py
  Spectogram.py
Labels: enhancement, new visualizer, gssoc, level2

#130 New GUI
  Index.py
  Installation.md
Labels: gssoc

#132 Add Title to Frequency Spectrum Plot and Improve Error Handling
  Amplitude-Frequency-Visualizer.py
Labels: enhancement, gssoc, level1

#135 Updated Spectogram.py
  Spectogram.py
Labels: enhancement, gssoc, level1

#134 added the website
  Amplitude-Frequency-Visualizer.py
  Intensity-vs-Frequency-and-time.py
  PCEN-noise_reduction.ipynb
  Real-Time VU Meter.py
  Spectogram.py
  Waveform.py
  index.html
  mainLanding.py
  requirements.txt
  scripts.js
  styles.css
Labels: documentation, gssoc, level3

#111 Added Spectral Gating
  Spectral_gating.ipynb
Labels: enhancement, gssoc, level2

#122 Rectifying Issue and added a feature for theme change : #121 and #123
  mainLanding.py
Labels: enhancement, gssoc, level2

#142 Added template for documentation issues
  .github/ISSUE_TEMPLATE/documentation.md
Labels: gssoc, level1

#156 added phase-spectrum to repo
  Phase-spectrum.py
Labels: enhancement, gssoc, level2

#153 Updated visualizers and mainpage using KIVY GUI
  Intensity-vs-Frequency-and-time.py
  Spectrogram.py
  Waveform.py
  mainLanding.py
Labels: enhancement, gssoc, level2
