Repository Soumya-Kushwaha/SoundScape, pull requests merged in 2024-07, with the labels that each got.

#161 added workflow for autocommenting on PR Merged
  .github/workflows/autocomment_on_PR_merge.yml
Labels: gssoc

#94 added feature of Frequency Vs Energy Plot of real time audio
  Frequency-Energy-plot.py
Labels: duplicate

#159 Improved the UI and updated two py files
  Amplitude-Frequency-Visualizer.py
  Energy-Frequency-Visualizer.py
  Intensity-vs-Frequency-and-time.py
  mainLanding.py
Labels: gssoc, level3

#171 Add a new Lissajous Curves Visualizer
  Lissajous-Curves-Visualizer.py
  mainLanding.py
Labels: gssoc, level3

#173 added Chroma-Feature-Visualizer
  Chroma-Feature-Visualizer.py
  mainLanding.py
  requirements.txt
Labels: gssoc, level3

#177 added Voxel Grid Visualizer
  Voxel-Grid-Visualizer.py
  mainLanding.py
Labels: gssoc, level2

#170 Added power-spectral-density curve
  Home.py
  Power-spectral-density.py
Labels: gssoc

#164 Added zero-crossing-line visualizer
  Zero-crossing-rate.py
Labels: gssoc, level3

#131 Added Workflow for closing issues on merging PR
  .github/workflows/close-on-merge.yml
Labels: enhancement, good first issue, gssoc, level1
